// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8QTmBETFhu7L8ET5GQq18xykTDEkcttg',
    appId: '1:1002735867588:web:e52a2d73a386b04dbc9b91',
    messagingSenderId: '1002735867588',
    projectId: 'evently-6caf0',
    authDomain: 'evently-6caf0.firebaseapp.com',
    storageBucket: 'evently-6caf0.firebasestorage.app',
    measurementId: 'G-11V5E6RLRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQWYDNpxGzbfiY4gh6NeeeZDebkuCu_w',
    appId: '1:1002735867588:android:61427b312df89513bc9b91',
    messagingSenderId: '1002735867588',
    projectId: 'evently-6caf0',
    storageBucket: 'evently-6caf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZ-VrnrCB5gpRQ9GnC9_48xA3-RZfzBQ',
    appId: '1:1002735867588:ios:5667374aadc16754bc9b91',
    messagingSenderId: '1002735867588',
    projectId: 'evently-6caf0',
    storageBucket: 'evently-6caf0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOZ-VrnrCB5gpRQ9GnC9_48xA3-RZfzBQ',
    appId: '1:1002735867588:ios:5667374aadc16754bc9b91',
    messagingSenderId: '1002735867588',
    projectId: 'evently-6caf0',
    storageBucket: 'evently-6caf0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8QTmBETFhu7L8ET5GQq18xykTDEkcttg',
    appId: '1:1002735867588:web:5b3c66ee99eef1cdbc9b91',
    messagingSenderId: '1002735867588',
    projectId: 'evently-6caf0',
    authDomain: 'evently-6caf0.firebaseapp.com',
    storageBucket: 'evently-6caf0.firebasestorage.app',
    measurementId: 'G-TQL6E5P90L',
  );
}
